app/models.py
import datetime
from flask import url_for
from app import db

class BasicSurvey(db.Document):
    created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
    title = db.StringField(max_length=255, required=True)

    # def get_absolute_url(self):
    #     return url_for('post', kwargs={"slug": self.slug})

    def __unicode__(self):
        return self.title

    # meta = {
    #     'allow_inheritance': True,
    #     'indexes': ['-created_at', 'slug'],
    #     'ordering': ['-created_at']
    # }


class BaseController(db.EmbeddedDocument):
    title = db.StringField(max_length=255, required=True)
    type = db.StringField(max_length=255, required=True)

    def __unicode__(self):
        return self.title

    meta = {'allow_inheritance': True}


class RadioButton(BaseController):
    def __init__(self, title):
        super(BaseController, self).__init__()
        self.title = title
        self.type = 'radiobutton'


class CheckBox(BaseController):
    def __init__(self, title):
        super(BaseController, self).__init__()
        self.title = title
        self.type = 'checkbox'


class BaseFormController(db.EmbeddedDocument):
    title = db.StringField(max_length=255, required=True)
    controllers = db.ListField(db.EmbeddedDocumentField('BaseController'))

    def __unicode__(self):
        return self.title

    meta = {'allow_inheritance': True}


class BaseForm(db.Document):
    title = db.StringField(max_length=255, required=True)
    controllers = db.ListField(db.EmbeddedDocumentField('BaseFormController'))

    def __unicode__(self):
        return self.title

    meta = {'allow_inheritance': True}

app/__init__.py
from flask import Flask
from config import Config
from flask.ext.mongoengine import MongoEngine


# def create_app():
#     app = Flask(__name__)
#     app.config["MONGODB_SETTINGS"] = {'DB': "MMCS_survey", 'alias':'default', host='localhost'}
#     app.config["SECRET_KEY"] = ""
#     db = MongoEngine().connection
#

#
#     return app, db
#
# app, db = create_app()

app = Flask(__name__)
app.config["MONGODB_SETTINGS"] = {'DB': "MMCS_survey", 'alias':'default', 'host':'localhost'}
app.config["SECRET_KEY"] = ""
from .main import main as main_blueprint
app.register_blueprint(main_blueprint)

from .survey import survey as survey_blueprint
app.register_blueprint(survey_blueprint,  url_prefix='/survey')
db = MongoEngine(app)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template
from . import main


@main.route('/')
def index():
    return render_template("index.html")

app/maintaining/__init__.py
from flask import Blueprint

maintaining = Blueprint('maintaining', __name__)

from . import views

app/maintaining/views.py
from flask import render_template
from . import maintaining


@maintaining.route('/maintaining')
def index():
    return render_template("maintaining.html")

app/survey/__init__.py
from flask import Blueprint

survey = Blueprint('survey', __name__)

from . import views

app/survey/views.py
from flask import render_template
from . import survey


@survey.route('/')
def index():
    return render_template("survey/index.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>

        <!-- Materialize and jQuery -->
        <link rel="stylesheet" href={{ url_for('static', filename = 'css/main.css') }}>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
        <script type="text/javascript" src={{ url_for('static', filename = 'js/main.js') }}></script>

    {% endblock %}
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

app/templates/components/card.html
{% block card %}
<div class="col s12 m4">
                    <div class="card">
                        <div class="card-image">
                            <img src="{% block image %}/static/img/sample.jpg{% endblock %}">
                            <span class="card-title"></span>
                        </div>
                        <div class="card-content">
                            <p>
                                {% block label %}
                                 Приняв участие в опросе,
                                 вы поможете улучшить качество преподаваемых дисциплин,
                                 повысить их доступность и актуальность
                                {% endblock %}
                            </p>
                        </div>
                    </div>
                </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %}Добро пожаловать!{% endblock %}
{% block body %}

    <br>
    <br>

    <div class='container center'>

        <h5>Институт математики, механики и компьютерных наук ЮФУ
в целях повышения образовательного качества проводит опрос студентов </h5>

        <br>
        <br>

        <a class="waves-effect waves-light btn center blue" href="{{ url_for('survey.index') }}">Принять участие</a>

        <br><br>
        <br><br>

        <div class="row">

            <div class="col s12 m4">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{ url_for('static', filename ='img/sample.jpg') }}">
                            <span class="card-title"></span>
                        </div>
                        <div class="card-content">
                            <p>
                                 Приняв участие в опросе,
                                 вы поможете улучшить качество преподаваемых дисциплин,
                                 повысить их доступность и актуальность
                            </p>
                        </div>
                    </div>
                </div>

             <div class="col s12 m4">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{ url_for('static', filename ='img/sample.jpg') }}">
                            <span class="card-title"></span>
                        </div>
                        <div class="card-content">
                            <p>
                                 Анонимность голосования достигается хранением идентификаторов
                                 проголосовавших без связывания их анкет с авторизационными данными
                            </p>
                        </div>
                    </div>
                </div>

            <div class="col s12 m4">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{ url_for('static', filename ='img/sample.jpg') }}">
                            <span class="card-title"></span>
                        </div>
                        <div class="card-content">
                            <p>
                                 Вы можете ознакомиться с актуальным исходным кодом проекта
                                 <a href="https://github.com/axazeano/MMCS_Survey" target="_blank">в репозитории на Github</a>
                            </p>
                        </div>
                    </div>
                </div>

        <!-- End of row -->
        </div>

    <!-- End of container -->
    </div>

    <footer class="page-footer lighten-3 blue">
    <div class="footer-copyright">
        <div class="container center">
              IT-лаборатория мехмата ЮФУ © 2015
        </div>
    </div>
    </footer>

{% endblock %}

app/templates/maintaining.html
{% extends 'base.html' %}
{% block title %}Администрирование системы анкетирования{% endblock %}
{% block body %}

    <nav class="blue lighten-2">
    <div class="nav-wrapper" style="position: relative; float: left">
      <ul id="nav-mobile" class="right hide-on-med-and-down">

              <input type="text" style="display: inline; float: left">
              <input type="text" style="display: inline; float: left;">
              <input type="text" style="display: inline">

      </ul>
    </div>
  </nav>

    <div class="full-center">
         <a class="waves-effect waves-light btn blue w-100">Создание анкет</a>
        <br><br>
         <a class="waves-effect waves-light btn blue w-100">Запуск опроса</a>
        <br><br>
         <a class="waves-effect waves-light btn blue w-100">Анализ результатов анкетирований</a>
    </div>

{% endblock %}

app/templates/survey/index.html
{% extends "base.html" %}
{% block title %}Принять участие{% endblock %}
{% block body %}
    <a class="btn">create survey</a>
{% endblock %}